name: QualityAssurance

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: yarn run lint
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2-beta
          with:
            node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: yarn test
